<html>

<head>
<title>登陆</title>
<link rel="stylesheet" href="content.CSS">
<link rel="stylesheet" type="text/css" href="3.css">
</head>

<body>
<center>
  <table width="679" border="0" bordercolor="#FF9900">
    <tr> 
      <td rowspan="3" width="9">　</td>
      <td width="646" height="15"></td>
      <td rowspan="3" width="10">　</td>
    </tr>
    <tr> 
      <td width="646" background="IMAGES/6.gif"> 
        <table border="0" width="87%" cellspacing="3" cellpadding="3" align="center">
          <tr> 
            <td align=center valign=middle class=shadow2> 
              <form action=Chkadmin.asp method=post>
                <br>
                用户名: 
                <input type=text size=15 maxlength=50 name=name value='' class=border>
                密码: 
                <input type=passwd size=15 maxlength=50 name=passwd class=border>
                <input type=submit value="登 录" name=send class=border>
                <input type=reset value="重 填" class=border name="reset"> <br>
&nbsp;<br>
              </form>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr> 
      <td width="646" height="20" bordercolor="#000000"> 
        <div align="center"><br>
        </div>
      </td>
    </tr>
  </table>
  </center>

</body>
</html>